### ISSUE TITLE
need helpppppp!!!!!!!!!

### ISSUE THREAD

**Issue by boxedbyZOE** [QuakedK/Oneclick#2]
I ran oneclick and now my Wi-Fi is off, Bluetooth doesn't work and, microsoft store is disabled pls help

**Comment by QuakedK** [comment]
# User error and failure to read the unsupported list

I'm going to have to hold you're hand when I say this, but read before doing things especially [Unsupported Features](https://github.com/QuakedK/Oneclick/blob/main/Unsupported%20Features.md). 
If you created a restore point manually or via oneclick, using that will revert any changes :)

![UF](https://github.com/user-attachments/assets/6dc06d05-8781-4146-b0e6-e88745085a7a)
