### ISSUE TITLE
Some settings reset to default upon pc restart and wifi and sound action menu doesn't work

### ISSUE THREAD

**Issue by chillzxvs** [QuakedK/Oneclick#4]
every time i restart my pc some settings like my display settings (monitor refresh rate goes back down to 60 and the 2 displays go on duplicate mode) and ever since i used the optimizer, the wifi and sound action menu on the taskbar pops up once i click it but instantly goes back down

**Comment by QuakedK** [comment]
I've heard nearly 10+ report of a similar issue, they all happen to be on 24H2. That version of windows is reportedly buggy.
Weather it a source from Xilly: https://www.tiktok.com/@x1lly/video/7433426996841188654?lang=en

Or any of my trusted sources that windows version seems to be the issue. And as stated win 11 22H2 is recommended!
win 11 22H2 Install: https://archive.org/details/windows11_20220930

**Comment by some-du6e** [comment]
lmao i fixed it by reseting my time
